repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: corefold
  description: General use pipeline for protein binder design
  author: Arman Thariani
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
